# Generated by Django 5.1.1 on 2024-09-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0002_user_is_active_user_is_staff_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
