# Generated by Django 5.1.1 on 2024-09-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0007_user_createdat_user_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
