# Generated by Django 5.1.1 on 2024-10-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0008_alter_user_createdat_alter_user_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.JSONField(null=True),
        ),
    ]
