# Generated by Django 5.1.1 on 2024-09-24 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_commenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='blog',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
